export const SU = [
  {
    id: 1,
    username: 'fabagile',
    firstname: 'Fabrice',
    lastname: 'Riquet',
    email: 'fabagile@outlook.fr',
    url: 'https://fabagile-portfolio.vercel.app',
    password: 'Majarade1',
    phone: '06 52 81 29 46',
    address: '3 rue du Rhin',
    addressMoreInfo: 'App 19',
    postalCode: '44470',
    city: 'Carquefou',
    creationDate: '2022-12-05T08:34:38.486Z',
    role: 'Administrateur',
    customerCategory: '',
    rootUser: true,
  },
];
